version: '3.1'

services:
  server:
    container_name: express-server
    build:
      context: .
      target: development
    command: npm run dev
    ports:
      - 8080:8080
    expose:
      - 8080
    develop:
      watch:
        - action: sync+restart
          path: ./
          target: /app
          ignore:
            - node_modules
            - package.json
            - package-lock.json
        - action: rebuild
          path: package.json
    depends_on:
      db:
        condition: service_healthy
    networks:
      - internal

  db:
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: nodedb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    ports:
      - 3306:3306
    expose:
      - 3306
    networks:
      - internal
    healthcheck:
      test:
        [
          "CMD",
          'mysqladmin',
          'ping',
          '-h',
          'localhost',
          '-u',
          'root',
          '-p$$MYSQL_ROOT_PASSWORD'
        ]
      timeout: 20s
      retries: 10

networks:
  internal:
    driver: bridge
